/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DcPopup {
    /**
    * Date
    */
    'date': string;
    /**
    * Hero
    */
    'hero': string;
    /**
    * URL
    */
    'url': string;
  }
}

declare global {


  interface HTMLDcPopupElement extends Components.DcPopup, HTMLStencilElement {}
  var HTMLDcPopupElement: {
    prototype: HTMLDcPopupElement;
    new (): HTMLDcPopupElement;
  };
  interface HTMLElementTagNameMap {
    'dc-popup': HTMLDcPopupElement;
  }
}

declare namespace LocalJSX {
  interface DcPopup {
    /**
    * Date
    */
    'date'?: string;
    /**
    * Hero
    */
    'hero'?: string;
    /**
    * URL
    */
    'url'?: string;
  }

  interface IntrinsicElements {
    'dc-popup': DcPopup;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'dc-popup': LocalJSX.DcPopup & JSXBase.HTMLAttributes<HTMLDcPopupElement>;
    }
  }
}


