/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DcFooter {
    }
}
declare global {
    interface HTMLDcFooterElement extends Components.DcFooter, HTMLStencilElement {
    }
    var HTMLDcFooterElement: {
        prototype: HTMLDcFooterElement;
        new (): HTMLDcFooterElement;
    };
    interface HTMLElementTagNameMap {
        "dc-footer": HTMLDcFooterElement;
    }
}
declare namespace LocalJSX {
    interface DcFooter {
    }
    interface IntrinsicElements {
        "dc-footer": DcFooter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dc-footer": LocalJSX.DcFooter & JSXBase.HTMLAttributes<HTMLDcFooterElement>;
        }
    }
}
